=== nicaa/MandatoryAssignment-sysint/src/XML/ProductOrder.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://xml.netbeans.org/schema/ProductOrder"
            xmlns:PO="http://xml.netbeans.org/schema/ProductOrder"
    xmlns:tns="http://xml.netbeans.org/schema/ProductOrder"
    elementFormDefault="qualified">

    <xsd:element name="PurchaseOrder" type="PO:PurchaseOrderType"/>
    
    <xsd:complexType name="PurchaseOrderType">
        <xsd:sequence>
            <xsd:element name="ShippingInformation" type="PO:Customer"/>
            <xsd:element name="Order" type="PO:OrderType"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="Customer">
        <xsd:complexContent>
            <xsd:extension base="PO:Address">
                <xsd:sequence>
                    <xsd:element name="FirstName" type="xsd:string"/>
                    <xsd:element name="LastName" type="xsd:string"/>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>
    
    <xsd:complexType name="Address">
        <xsd:sequence>
            <xsd:element name="Street" type="xsd:string"/>
            <xsd:element name="PostalCode" type="xsd:string"/>
            <xsd:element name="City" type="xsd:string"/>
            <xsd:element name="Country" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="OrderType">
        <xsd:sequence>
            <xsd:element name="Item" type="PO:OrderItem" maxOccurs="unbounded"/>
            <xsd:element name="TotalPrice">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:minInclusive value="100"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="OrderItem">
        <xsd:sequence>
            <xsd:element name="Product" type="xsd:string"/>
            <xsd:element name="Price" type="xsd:integer"/>
        </xsd:sequence>
    </xsd:complexType>
    
</xsd:schema>

=== nicaa/MandatoryAssignment-sysint/src/XML/productOrderOutput.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
--><ns1:PurchaseOrder xmlns:ns1="http://xml.netbeans.org/schema/ProductOrder" xmlns="http://xml.netbeans.org/schema/ProductOrder" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xml.netbeans.org/schema/ProductOrder ProductOrder.xsd">
    <ns1:ShippingInformation>
        <ns1:Street>Stairway</ns1:Street>
        <ns1:PostalCode>2400</ns1:PostalCode>
        <ns1:City>Copenhagen</ns1:City>
        <ns1:Country>Denmark</ns1:Country>
        <ns1:FirstName>Rasmus</ns1:FirstName>
        <ns1:LastName>Hojte</ns1:LastName>
    </ns1:ShippingInformation>
    <ns1:Order>
        <ns1:Item>
            <ns1:Product>Apple</ns1:Product>
            <ns1:Price>50</ns1:Price>
        </ns1:Item>
        <ns1:Item><ns1:Product>Banana</ns1:Product><ns1:Price>125</ns1:Price></ns1:Item>
        <ns1:Item>
            <ns1:Product>Orange</ns1:Product>
            <ns1:Price>75</ns1:Price>
        </ns1:Item>
        
        <ns1:TotalPrice>100</ns1:TotalPrice>
    </ns1:Order>

</ns1:PurchaseOrder>

=== nicaa/MandatoryAssignment-sysint/src/XML/unrulyProductOrder.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<PurchaseOrder
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='ProductOrder.xsd'>
    <ShippingInformation>
        <Street>John Doe Street</Street>
        <PostalCode>5555</PostalCode>
        <City>John Doe City</City>
        <Country>JD Country</Country>
        <FirstName>John</FirstName>
        <LastName>Doe</LastName>
    </ShippingInformation>
    <Order>
        <Item>
            <Product>Banana</Product>
            <Price>10</Price>
        </Item>
        <Item>
            <Product>Apple</Product>
            <Price>15</Price>
        </Item>
        <Item>
            <Product>Pear</Product>
            <Price>100</Price>
        </Item>
        <TotalPrice>100</TotalPrice>
    </Order>

</PurchaseOrder>

=== nicaa/MandatoryAssignment-sysint/src/XML/productOrder.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<ns1:PurchaseOrder
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns1='http://xml.netbeans.org/schema/ProductOrder'
    xsi:schemaLocation='http://xml.netbeans.org/schema/ProductOrder ProductOrder.xsd'>
    <ns1:ShippingInformation>
        <ns1:Street>Stairway</ns1:Street>
        <ns1:PostalCode>2400</ns1:PostalCode>
        <ns1:City>Copenhagen</ns1:City>
        <ns1:Country>Denmark</ns1:Country>
        <ns1:FirstName>Rasmus</ns1:FirstName>
        <ns1:LastName>Hojte</ns1:LastName>
    </ns1:ShippingInformation>
    <ns1:Order>
        <ns1:Item>
            <ns1:Product>Apple</ns1:Product>
            <ns1:Price>50</ns1:Price>
        </ns1:Item>
        <ns1:Item>
            <ns1:Product>Banana</ns1:Product>
            <ns1:Price>50</ns1:Price>
        </ns1:Item>
        
        <ns1:TotalPrice>100</ns1:TotalPrice>
    </ns1:Order>

</ns1:PurchaseOrder>
